name: Deploy Supabase services
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-functions:
    name: Deploy functions
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: supabase/setup-cli@v1
        with:
          version: latest
      - name: Deploy Supabase functions
        run: supabase functions deploy --project-ref $SUPABASE_PROJECT_ID --no-verify-jwt
        env:
          SUPABASE_PROJECT_ID: ${{secrets.SUPABASE_PROJECT_ID}}
          SUPABASE_ACCESS_TOKEN: ${{secrets.SUPABASE_ACCESS_TOKEN}}

  # Temporarily commented out - skip run-migrations for now
  # run-migrations:
  #   name: Run migrations
  #   runs-on: ubuntu-latest
  #   needs: [deploy-functions]
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: supabase/setup-cli@v1
  #       with:
  #         version: latest
  #     - name: Push database changes
  #       run: |
  #         supabase link --project-ref $SUPABASE_PROJECT_ID
  #         supabase db push
  #       env:
  #         SUPABASE_DB_PASSWORD: ${{secrets.DB_PASSWORD}}
  #         SUPABASE_PROJECT_ID: ${{secrets.SUPABASE_PROJECT_ID}}
  #         SUPABASE_ACCESS_TOKEN: ${{secrets.SUPABASE_ACCESS_TOKEN}}
